<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Incorrect email or password.' => 'Erreur d\'email ou de mot de passe.',
    'First Name cannot be blank.' => 'Merci de remplir votre prénom.',
    'Last Name cannot be blank.' => 'Merci de remplir votre nom.',
    'Gender cannot be blank.' => 'Merci de préciser votre sexe.',
    'Attribute cannot be blank.' => 'Les champs suivants sont obligatoire.',
    'Email cannot be blank.' => 'Merci de remplir votre e-mail.',
    'Password cannot be blank.' => 'Merci de remplir votre mot de passe',
    'New Password cannot be blank.' => 'Merci de remplir votre nouveau mot de passe.',
    'Email is not a valid email address.' => 'Votre adresse email est invalide.',
    'There is no user with such email.' => 'Cette adresse e-mail ne correspond à aucun utilisateur.',
    'Following password is incorrect.' => 'Le Mot de passe est incorrecte.',
    'Password must be no less than {min}.' => 'Votre mot de passe  doit contenir au moins {min} caractères.',
    'Confirm Password cannot be blank.' => 'Merci de confirmer votre mot de passe.',
    'Passwords do not match.' => 'Les mots de passes sont différents.',
    'Attribute must be no greater than {max}.' => 'La valeur de ces champs ne doivent pas depasser {max}.',
    'Attribute has already been taken.' => 'Les champs suivants sont déjà pris.',
    'Attribute must be an integer.' => 'Les champs suivants  doivent contenir un nombre entier',
    'Incorrect attribute value.' => 'Valeur  du champs incorrecte',
    'Date format is incorrect.' => 'le format de la date est incorrecte',
    'Only files with these extensions are allowed: jpg, gif, png.' => 'Formats de fichiers autorisés : jpg, gif, png.',
    'Only files with these extensions are allowed: gpx.' => 'Format de fichiers autorisé :  gpx.',
    'Weight format is incorrect.' => 'Le format du poids est incorrecte.',
    'The file is too big.' => 'le poids de votre fichier est trop important.',
    'Following request does not exists.' => 'la demande suivante n\'existe pas',
    'Following user does not exists.' => 'l\'utilisateur suivant n\'existe pas.',
    'Following request incorrect.' => 'La demande suivante est incorrecte.',
    'Following request already in use.' => 'la demande suivante est déjà en cours',
    'Communication error has been detected.' => 'Une erreur de communication a été détectée.',
    'Average Speed format is incorrect.' => 'Le format de la vitesse moyenne est incorrecte.',
    'Attribute must contain latitude key' => 'Ces champs doivent contenir une latitude.',
    'Attribute must contain longitude key' => 'Ces champs doivent contenir une longitude.',
    'Attribute does not have required data' => 'Ces champs n\'ont pas les informations requises.',
    'Incorrect attribute type' => 'information du mauvais type.'
];